name: Como usar variavel de ambiente e contexto do GitHub Actions
on: 
    push:
        branches: [main]
env:
  ENV_WORKFLOW: "Valor WORKFLOW"
jobs:
  enviroment:
    runs-on: ubuntu-latest
    env:
        ENV_JOB: "Valor JOB"
    steps:
      - name: Variáveis de Ambiente
        env:
          ENV_ACTIONS: "Valor ACTIONS"
        run: | 
          echo "$ENV_WORKFLOW" 
          echo "$ENV_JOB"
          echo "$ENV_ACTIONS"
  contextos:
    runs-on: ubuntu-latest
    env:
        ENV_JOB: "Valor JOB CONTEXT"
    steps:
      - name: Contexto github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Contexto env
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
      - name: Contexto job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Contexto steps
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Contexto runner
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
  variables:
    runs-on: ubuntu-latest
    steps:
    - name: Contexto vars
      env:
        VARS_CONTEXT: ${{ toJson(vars) }}
      run: echo "$VARS_CONTEXT"
  secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Contexto vars
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
      run: echo "$SECRETS_CONTEXT"